version: '3.9'

services:
  autofacturabackend:
    image: autofacturabackend
    build:
      context: .
      dockerfile: .docker/Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --listen 0.0.0.0:5678 -m uvicorn fastapi_app.application:app --host 0.0.0.0 --port 8000"]
    ports:
      - 8000:8000
      - 5678:5678

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: 1998.ruben26@gmail.com 
      PGADMIN_DEFAULT_PASSWORD: 260316@a
    ports:
      - "8081:80"
    depends_on:
      - rdbms
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pgadmin_data:
    name: pgadmin_data