version: '3.4'

services:
  autofacturabacked:
    image: autofacturabacked
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    ports:
      - 8000:8000
  
  db:
    image: postgres:16.3
    container_name: postgres_container
    environment:
      POSTGRES_USER: gubene
      POSTGRES_PASSWORD: 260316@
      POSTGRES_DB: db_receip
    ports: 
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: 1998.ruben26@gmail.com 
      PGADMIN_DEFAULT_PASSWORD: 260316@a
    ports:
      - "8081:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
  
  rabbitqm:
    image: rabbitmq:management
    container_name: rabbitqm_container
    ports:
      - "5672:5672"  # Puerto para la comunicación AMQP
      - "15672:15672"  # Puerto para el panel de administración web
    environment:
      RABBITQM_DEFAULT_USER : "guest"
      RABBITQM_DEFAULT_PASSWORD: "guest"
    volumes:
      - rabbitqm_data:/var/lib/rabbitqm
  
  mongodb:
    image : mongo:5.0
    container_name: mongo_container
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=gubene
      - MONGO_INITDB_ROOT_PASSWORD=mongorubius
    volumes:
      - mongodata:/data/db


# recordar agregar a gitignore los volumenes
volumes:
  postgres_data:
   name: postgres_data
  pgadmin_data:
    name: pgadmin_data
  rabbitqm_data:
    name: rabbitqm_data
    driver : local
  mongodata : 
    name: mongodata
  