"""Added catalog seeds

Revision ID: cb6cf2a7570d
Revises: 727bc2e439b9
Create Date: 2024-09-09 08:04:09.588635

"""

from typing import Sequence, Union
from uuid import UUID

from sqlalchemy.orm import Session

from alembic import op
from modules.document_types.domain.entities.document_type import DocumentType
from modules.issuer.domain.entities.issuer import Issuer

# revision identifiers, used by Alembic.
revision: str = "cb6cf2a7570d"
down_revision: Union[str, None] = "51c81419f36f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = Session(bind=bind)

    ticket_type = DocumentType(
        id=UUID("a9e39cc9-1749-4da6-b271-cd71cd0481df"),
        name="ticket",
        label="Ticket",
        description="Ticket provided by an issuer. This is not a taxable invoice yet.",
    )
    invoice_type = DocumentType(
        id=UUID("f46f1186-5e20-456b-a2b4-190823cc7fe4"),
        name="invoice",
        label="Factura",
        description="Factura para impuestos. Esto es un CFDI. Se puede utilizar para declara impuestos.",
    )
    tax_certificate_type = DocumentType(
        id=UUID("03a863d3-7570-41a0-8046-1c05c4c2b6e2"),
        name="tax_certificate",
        label="Constancia de Situación Fiscal",
        description="Constancia de situación fiscal emitida por el SAT.",
    )
    walmart = Issuer(
        id=UUID("e476735e-e94a-4590-9d30-f4aea38fcf66"),
        name="walmart",
        label="Walmart",
        description="Supermercado de retail minorista Walmart",
    )
    aurrera = Issuer(
        id=UUID("0190e6bc-1d35-464c-8017-4c2d7249dd91"),
        name="aurrera",
        label="Bodega Aurrera",
        description="Bodega Aurrera es una tienda de conveniencia en México creado en el año 1970, que fue originalmente propiedad de la empresa mexicana Almacenes Aurrerá, y actualmente de la filial mexicana del corporativo detallista estadounidense Walmart.",
    )
    oxxo = Issuer(
        id=UUID("ab04cceb-ce71-4279-bcce-538d19fe2ff2"),
        name="oxxo",
        label="Oxxo",
        description="Cadena multinacional de tiendas de conveniencia mexicana, propiedad de FEMSA, fundada en Guadalupe, Nuevo León, México en 1978, subsidiaria de FEMSA Comercio, S.A. de C.V., y con su sede en Monterrey, Nuevo León, que actualmente cuenta con alrededor de 21,000 ubicaciones tanto en México como otros países de Latinoamérica, y también tiene presencia en los Estados Unidos y España.",
    )

    # Seed data
    session.add_all(
        [ticket_type, invoice_type, tax_certificate_type, walmart, aurrera, oxxo]
    )
    session.commit()
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
